@baseUrl = http://localhost:5259
@tournamentName = Premier League 2026
@startDate = 2026-08-15T00:00:00Z
@maxTeams = 20

###

# @name createTournament
POST {{baseUrl}}/tournaments/
Content-Type: application/json

{
  "name": "{{tournamentName}}",
  "startDate": "{{startDate}}",
  "maxTeams": {{maxTeams}}
}

###

GET {{baseUrl}}/tournaments/
Accept: application/json

###

GET {{baseUrl}}/tournaments/{{createTournament.response.body.$.id}}
Accept: application/json

###

# Duplicate name (should return 400)
POST {{baseUrl}}/tournaments/
Content-Type: application/json

{
  "name": "{{tournamentName}}",
  "startDate": "{{startDate}}",
  "maxTeams": {{maxTeams}}
}

###

# Validation error - empty fields (should return 400)
POST {{baseUrl}}/tournaments/
Content-Type: application/json

{
  "name": "",
  "startDate": "2026-08-15T00:00:00Z",
  "maxTeams": 0
}

###

# Not found (should return 404)
GET {{baseUrl}}/tournaments/11111111-1111-1111-1111-111111111111
Accept: application/json

###

# Add a team to a tournament (use IDs from createTournament and a created team)
# @name addTeam
POST {{baseUrl}}/tournaments/71a2a10a-7b1d-4a0e-a8fc-319f6d54c92b/teams
Content-Type: application/json

{
  "teamId": "REPLACE_WITH_TEAM_ID"
}

###

# Get all teams in a tournament
GET {{baseUrl}}/tournaments/{{createTournament.response.body.$.id}}/teams
Accept: application/json

###

# Add team to non-existent tournament (should return 404)
POST {{baseUrl}}/tournaments/11111111-1111-1111-1111-111111111111/teams
Content-Type: application/json

{
  "teamId": "22222222-2222-2222-2222-222222222222"
}
